export const fonts = {
  sans: {
    thin: 'Geist-Thin',
    thinItalic: 'Geist-ThinItalic',
    extraLight: 'Geist-ExtraLight',
    extraLightItalic: 'Geist-ExtraLightItalic',
    light: 'Geist-Light',
    lightItalic: 'Geist-LightItalic',
    regular: 'Geist',
    regularItalic: 'Geist-RegularItalic',
    medium: 'Geist-Medium',
    mediumItalic: 'Geist-MediumItalic',
    semiBold: 'Geist-SemiBold',
    semiBoldItalic: 'Geist-SemiBoldItalic',
    bold: 'Geist-Bold',
    boldItalic: 'Geist-BoldItalic',
    extraBold: 'Geist-ExtraBold',
    extraBoldItalic: 'Geist-ExtraBoldItalic',
    black: 'Geist-Black',
    blackItalic: 'Geist-BlackItalic',
  },
  mono: {
    thin: 'GeistMono-Thin',
    thinItalic: 'GeistMono-ThinItalic',
    extraLight: 'GeistMono-ExtraLight',
    extraLightItalic: 'GeistMono-ExtraLightItalic',
    light: 'GeistMono-Light',
    lightItalic: 'GeistMono-LightItalic',
    regular: 'GeistMono',
    italic: 'GeistMono-Italic',
    medium: 'GeistMono-Medium',
    mediumItalic: 'GeistMono-MediumItalic',
    semiBold: 'GeistMono-SemiBold',
    semiBoldItalic: 'GeistMono-SemiBoldItalic',
    bold: 'GeistMono-Bold',
    boldItalic: 'GeistMono-BoldItalic',
    extraBold: 'GeistMono-ExtraBold',
    extraBoldItalic: 'GeistMono-ExtraBoldItalic',
    black: 'GeistMono-Black',
    blackItalic: 'GeistMono-BlackItalic',
  },
};